# Generated by Django 4.2.1 on 2023-06-01 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=120, verbose_name='Почта')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=45, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('department', models.IntegerField(max_length=50, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название номенклатуры')),
                ('create_date', models.DateTimeField(verbose_name='Дата и время создания')),
                ('file', models.BinaryField(max_length=255, verbose_name='Файл')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.user')),
            ],
        ),
    ]
