# Generated by Django 4.2.1 on 2023-06-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_alter_nomenclature_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
