# Generated by Django 4.2.1 on 2023-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_alter_nomenclature_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='link',
            field=models.CharField(default='', editable=False, max_length=10, verbose_name='Сгенерированная ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файл номенклатуры'),
        ),
    ]
