# Generated by Django 4.2.1 on 2023-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_nomenclature_link_alter_nomenclature_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл номенклатуры')),
            ],
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='file',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='files',
            field=models.ManyToManyField(to='myproject.file', verbose_name='Файлы номенклатуры'),
        ),
    ]
