# Generated by Django 4.2.1 on 2023-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_remove_nomenclature_files_nomenclature_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='file',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='files',
            field=models.ManyToManyField(to='myproject.file'),
        ),
    ]
