# Generated by Django 4.2.1 on 2023-06-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_file_remove_nomenclature_file_nomenclature_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='nomenclature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myproject.nomenclature'),
            preserve_default=False,
        ),
    ]
