# Generated by Django 4.2.1 on 2023-06-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_remove_file_nomenclature_nomenclature_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='file',
            name='linked_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.nomenclature'),
        ),
    ]
