# Generated by Django 4.2.1 on 2023-06-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_alter_file_options_file_linked_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='linked_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.nomenclature'),
        ),
    ]
