# Generated by Django 4.2.1 on 2023-06-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_alter_file_linked_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='linked_to',
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Адрес файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название файла'),
        ),
    ]
