# Generated by Django 4.2.1 on 2023-06-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_remove_file_linked_to_file_status_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='linked_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.nomenclature'),
        ),
    ]
